services:
  - type: web
    name: mge-heroes-api
    env: docker  # <- Змінено на Docker
    region: oregon
    plan: free
    dockerfilePath: ./MGE_HEROES.Server/Dockerfile  # Шлях до Dockerfile, якщо не в корені
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:$PORT
      - key: JWT__SecretKey
        sync: false
      - key: JWT__Issuer
        value: mge-heroes-app
      - key: JWT__Audience
        value: mge-heroes-users
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
    autoDeploy: true

databases:
  - name: mge-heroes-db
    databaseName: mge_db
    user: mge_user
    region: oregon
    plan: free